#!/usr/bin/env python3

import os


def build(bld):
    if not bld.env.HAS_GTEST:
        bld.fatal('MotorBlimp controller tests require gtest; reconfigure SITL without --disable-tests')

    source_dir = os.environ.get('ARDUMOTORBLIMP_SOURCE_DIR')
    if source_dir is None:
        source_dir = os.path.dirname(os.path.realpath(bld.path.abspath()))
    source_dir = os.path.realpath(source_dir)
    source_node = bld.root.find_node(source_dir)
    if source_node is None:
        bld.fatal('Cannot find ArduMotorBlimp source directory: %s' % source_dir)

    required_sources = [
        source_node.find_resource('MotorMixer.cpp'),
        source_node.find_resource('FlightControl.cpp'),
    ]
    if any(source is None for source in required_sources):
        bld.fatal('MotorMixer.cpp or FlightControl.cpp is missing from %s' % source_dir)

    features = ['test'] if bld.cmd == 'check' else []
    bld.ap_program(
        features=features,
        includes=[source_dir, bld.srcnode.abspath() + '/tests'],
        source=[bld.path.find_resource('test_motorblimp_control.cpp')] + required_sources,
        use=['ap', 'GTEST'],
        program_name='test_motorblimp_control',
        program_groups='tests',
        use_legacy_defines=False,
        vehicle_binary=False,
        cxxflags=['-Wno-undef'],
    )
